FROM confluentinc/cp-kafka-connect:7.5.1
# Install a simple generator to verify Connect works.RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.4E
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.4
